// Unit tests for the Worker input table. They run in Node and never start workerd.
//
// The cases that matter are the ones a hand-maintained path list got wrong: config files that are
// not source, and derived output that must not look like input.

import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, it } from "vitest";
import { isWorkerInput, WATCH_PATHS } from "../src/worker-inputs.js";

const WORKSPACE_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const inWorkspace = (path: string) => resolve(WORKSPACE_DIR, path).replaceAll("\\", "/");

it.each([
  // Not source, but they decide what wrangler loads: `typed-storage` is the one package that emits,
  // and these three control that emit.
  "packages/typed-storage/tsconfig.json",
  "packages/typed-storage/package.json",
  "tsconfig.json",
  "packages/workshop-backend/src/server.ts",
  "packages/workshop-backend/wrangler.jsonc",
  "packages/workshop-shared/src/api.ts",
  "packages/integration-tests/fixtures/gatekeeper-test/wrangler.jsonc",
  "packages/integration-tests/fixtures/gatekeeper-test/src/test-gatekeeper.ts",
  "pnpm-lock.yaml",
])("treats %s as a Worker input", path => {
  expect(isWorkerInput(inWorkspace(path))).toBe(true);
});

it.each([
  // Generated by the build this suite triggers; watching it would let a rebuild trigger itself.
  "packages/workshop-backend/src/generated/format-blueprints.ts",
  "packages/typed-storage/dist/index.js",
  "packages/workshop-backend/.wrangler/validate/src/server.ts",
  "packages/integration-tests/fixtures/gatekeeper-test/.wrangler/validate/src/test-gatekeeper.ts",
  "packages/workshop-backend/node_modules/capnweb/index.js",
  "packages/typed-storage/node_modules/.bin/tsc",
  // Another package's tests reach the Worker through none of this.
  "packages/workshop-frontend/src/main.tsx",
])("does not treat %s as a Worker input", path => {
  expect(isWorkerInput(inWorkspace(path))).toBe(false);
});

// Each entry's own root is what `server.watcher.add` receives, so a file directly inside any of
// them must sit under a watched path -- otherwise the predicate above accepts events that never
// arrive.
const covered = (path: string) =>
  WATCH_PATHS.some(root => path === root || path.startsWith(`${root}/`));

it("watches a root covering every entry in the table", () => {
  const roots = [
    "packages/workshop-backend",
    "packages/workshop-backend/src",
    "packages/workshop-shared",
    "packages/backend-utils",
    "packages/error-reporting",
    "packages/typed-storage",
    // The one entry the environment can move, resolved as the blueprint generator resolves it.
    resolve(
      WORKSPACE_DIR,
      "packages/workshop-backend",
      process.env.FORMAT_BLUEPRINTS_DIR ?? "format-blueprints",
    ),
    "packages/integration-tests/fixtures",
    "packages/integration-tests/fixtures/gatekeeper-test",
    "tsconfig.json",
    "pnpm-lock.yaml",
  ].map(inWorkspace);

  expect(roots.filter(root => !covered(root))).toEqual([]);
  expect(WATCH_PATHS.length).toBe(roots.length);
});
