import {
  vitestTaskWithExclusions,
  withTestTimeout,
  VITEST_TOOL_SCRATCH_EXCLUSIONS,
  WRANGLER_RUNTIME_SCRATCH_EXCLUSIONS,
} from '@gadgets/scripts/vitest-task'

export default {
  run: {
    tasks: {
      /** Builds the fixture and orders both validated Workers before test files start. */
      'build:test-gatekeeper': {
        command: withTestTimeout(
          'capnweb-validate build --cwd fixtures/gatekeeper-test --out .wrangler/validate',
        ),
        cache: false,
        dependsOn: ['@gadgets/workshop-backend#build:integration-worker'],
      },
      /**
       * The one suite that keeps `.wrangler/validate` in its fingerprint instead of excluding it.
       *
       * Everywhere else that tree is regenerated by the same task that reads it, so it is both
       * unusable as an input and redundant with the sources vitest reads directly. Here both
       * trees -- workshop-backend's and the fixture gatekeeper's -- are pure input: neither
       * worker rebuilds during the run (`src/global-setup.ts` sets
       * `WORKSHOP_INTEGRATION_PREBUILT` and `src/harness.ts` deletes the Workshop's
       * `config.build` in response; the fixture's `wrangler.jsonc` declares no build at all), and
       * both producers have already run as this task's dependencies. Backend source reaches this
       * suite through those trees and nowhere else, so excluding them would leave the fingerprint
       * with no backend information at all. capnweb-validate's output is byte-deterministic, so
       * tracking them invalidates on real changes only.
       *
       * That leaves the shared vitest scratch paths plus the two wrangler trees this run really
       * does write: `tmp/` (per-boot bundles) and `state/` (local DO/KV storage).
       */
      test: {
        ...vitestTaskWithExclusions('vitest run', [
          ...VITEST_TOOL_SCRATCH_EXCLUSIONS,
          ...WRANGLER_RUNTIME_SCRATCH_EXCLUSIONS,
        ]),
        dependsOn: ['build:test-gatekeeper'],
      },
    },
  },
}
