#!/usr/bin/env node

// Single command to try out the Gadgets Workshop locally:
//
//   1. Installs dependencies (if needed).
//   2. Builds only what's required to *run* the app:
//        - @gadgets/typed-storage  (the backend imports it via its built `dist` output)
//        - the frontend bundle     (`vite build` -> packages/workshop-frontend/dist)
//      Gatekeeper configurator files are generated by run-dev-server.ts at startup.
//   3. Launches the local server (run-dev-server.ts --serve-frontend-assets), which serves the
//      built frontend as static assets on the backend.
//
// Vite+ owns the build cache and restores missing outputs on warm runs.

import { execFileSync, spawn } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getDevServerConfig } from "./dev-server-config.ts";
import { pnpmCommand } from "./pnpm-command.ts";
import { relayTermination } from "./relay-termination.ts";
import { vpRunEnv } from "./vp/concurrency.ts";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));

// Machine-aware `vp run` concurrency (vp/concurrency.ts). Computed once, so the note prints once, and
// handed to the dev server too, which then sees the variable already set and stays silent.
const env = vpRunEnv();

// Forward any extra flags (e.g. --use-workers-ai-binding) on to run-dev-server.ts.
const passthroughArgs = process.argv.slice(2);
let backendHost: string;
try {
  ({ backendHost } = getDevServerConfig(passthroughArgs, process.env.VITE_BACKEND_HOST));
} catch (err) {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
}


function runPnpm(args: string[]): void {
  console.log(`\n> pnpm ${args.join(" ")}`);
  const [command, argv] = pnpmCommand(args);
  execFileSync(command, argv, { stdio: "inherit", cwd: ROOT, env });
}

runPnpm(["install"]);
runPnpm(["exec", "vp", "run", "--cache", "@gadgets/typed-storage#build"]);
runPnpm(["exec", "vp", "run", "--cache", "@gadgets/workshop-frontend#build:assets"]);

// ---------------------------------------------------------------------------
// Launch the local server (serves the built frontend as static assets).
// ---------------------------------------------------------------------------

console.log(`\nStarting local server at http://${backendHost} ...`);
const server = spawn(
    process.execPath,
    [join(ROOT, "scripts", "run-dev-server.ts"), "--serve-frontend-assets", ...passthroughArgs],
    { stdio: "inherit", cwd: ROOT, env });

// Signals reach the whole server tree, not just run-dev-server itself (relay-termination.ts).
// Known limitation, not worth the restructuring to fix: the pre-flight steps above are
// `execFileSync`, which blocks the event loop, so a signal arriving during `pnpm install` is not
// forwarded until that call returns.
relayTermination(server);
